[package]
name = "msaada"
version = "0.1.0"
edition = "2021"
authors = ["Vincent Bruijn <vebruijn@gmail.com>"]
description = "Serve a directory as document root over a given port. This is a development tool."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
actix-files = "0.6"
env_logger = "0.10"
log = "0.4"
clap = "4.4.3"

[profile.release]
opt-level = 3
